### PR TITLE
Add functionalities relate to bank account (i.e. delete, set default)

### LINKED ISSUE #39: Delete & set default bank account functionalities
Just a quick issue :woozy_face:

### PR DESCRIPTION
**Pull request by EnderWolf50**
Trying to resolve #39 

Additional changes:
* the `mui-one-time-password` package was downgraded back to `^1.2.5`. I discovered this issue before but somehow I just accidentaly upgrade it... 😕 

*Note: The request seems to be firing correctly, but I haven't done a full test of the backend because I don't have the AWS credentials set up after reinstalling Windows blah blah blah*

### CODE REVIEW

**Comment by EnderWolf50** [comment]
@sh1un hiiiii I think u can check this PR

I didn't do a full test instead I just inspect network tab in devtool and it seems everything works
However u might want to do a more detailed test or smth idk I'll just build a church for u
```
                  _|_
                   |
                  / \
                 //_\\
                //(_)\\
                 |/^\| 
       ,%%%%     // \\    ,@@@@@@@,
     ,%%%%/%%%  //   \\ ,@@@\@@@@/@@,
 @@@%%%\%%//%%%// === \\ @@\@@@/@@@@@
@@@@%%%%\%%%%%// =-=-= \\@@@@\@@@@@@;%#####,
@@@@%%%\%%/%%//   ===   \\@@@@@@/@@@%%%######,
@@@@@%%%%/%%//|         |\\@\\//@@%%%%%%#/####
'@@@@@%%\\/%~ |         | ~ @|| %\\//%%%#####;
  @@\\//@||   |  __ __  |    || %%||%%'######
   '@||  ||   | |  |  | |    ||   ||##\//####
     ||  ||   | | -|- | |    ||   ||'#||###'
     ||  ||   |_|__|__|_|    ||   ||  ||
     ||  ||_/`  =======  `\__||_._||  ||
   __||_/`      =======            `\_||___
   ```

**Comment by sh1un** [comment]
Hi @EnderWolf50 

Please check the following bugs

- [ ] 1. 設為預設帳號，Unhandled Runtime Error TypeError: confirm is not a function
    * [ img1-1 ]
image
    * [ img1-2 ]    
image

```javascript
src\pages\users\me\payments\[bankAccId].tsx (132:10) @ confirm
 130 | } = useSetDefaultBankAccount();
  131 | const handleClick = async () => {
> 132 |   await confirm({
      |        ^
  133 |     title: "確認要變更預設帳號嗎？"
  134 |   });
  135 |   requestOtp();

```
```javascript 
DevTools Console

[bankAccId].tsx:132 Uncaught (in promise) TypeError: confirm is not a function
    at handleClick ([bankAccId].tsx:132:11)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4291:1)
    at executeDispatch (react-dom.development.js:9041:1)
    at processDispatchQueueItemsInOrder (react-dom.development.js:9073:1)
    at processDispatchQueue (react-dom.development.js:9086:1)
    at dispatchEventsForPlugins (react-dom.development.js:9097:1)
    at eval (react-dom.development.js:9288:1)
    at batchedUpdates$1 (react-dom.development.js:26140:1)
    at batchedUpdates (react-dom.development.js:3991:1)
    at dispatchEventForPluginEventSystem (react-dom.development.js:9287:1)
    at dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay (react-dom.development.js:6465:1)
    at dispatchEvent (react-dom.development.js:6457:1)
    at dispatchDiscreteEvent (react-dom.development.js:6430:1)
```

**Comment by EnderWolf50** [comment]
@sh1un I think both of them should have been fixed now.

_note: I finally decide to move `/payments` to `/bank-accounts`, and thus, there's some file changes out of this issue/PR's scope_

**Comment by sh1un** [comment]
Hi @EnderWolf50 

Please check the following bug

- [ ] 1. 設定銀行預設帳號 PATCH /bank-accounts/{bankAccountId}/default，後端錯誤顯示未傳 `otpCode`
    * [ img1-1 ]
image

**Comment by EnderWolf50** [comment]
@sh1un sorry I forgot to send payload when firing patch request 😔

**Comment by sh1un** [comment]
@EnderWolf50 , LGTM !

**Review by sh1un — APPROVED** [review]

**Pull request merged**
