### PR TITLE
Add "click avatar to the user's page" feature

### PR DESCRIPTION
**Pull request by EnderWolf50**
title.

sry kind of lazy to think PR message msg recently

### CODE REVIEW

**Comment by EnderWolf50** [comment]
@sh1un 🙏

**Comment by sh1un** [comment]
@EnderWolf50 
我很抱歉需求沒有講明確
是否能在點擊"名字"的部分，也加上同樣的功能(跳轉至會員詳情頁面)

**Comment by EnderWolf50** [comment]
@sh1un bump

**Comment by sh1un** [comment]
Hi @EnderWolf50 

Please check the following issues

- [ ] 1. 已出價代購者，出價者的名稱未 implement 
    * [ img1-1 ]
image
- [ ] 2. 接受報價 Dialog，出價者名稱 尚未 Implement
    * [ img2-1 ]
image

**Pull request merged**
